name: Lint
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools
          python3 -m pip install poetry==1.0.9
          poetry config virtualenvs.create false
          poetry install
      - run: pylint mergecounts
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: lgeiger/black-action@v1.0.1
        with:
          args: "mergecounts --check"
  # mypy:
  #   name: Check type annotations with MyPy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2
  #     - name: Setup Python
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: '3.8'
  #     - run: pip install --no-cache-dir poetry
  #     - run: poetry install
  #     - run: which python
  #     - run: poetry run mypy mergecounts --strict
